# Generated by Django 6.0.7 on 2026-08-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='emr.visit'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
    ]
