# Generated by Django 6.0.7 on 2026-08-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(default='MRN-66F34BCD', editable=False, max_length=20, unique=True),
        ),
    ]
