# Generated by Django 6.0.7 on 2026-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_medical_record_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(default='MRN-30B6BEC2', editable=False, max_length=20, unique=True),
        ),
    ]
